### PR TITLE
Interpret zwave supported_features attr as bitmask

### PR DESCRIPTION
**Pull request by hwhesselink**
Hi @DBuit, groeten van een medelander in California:-)

The Z-Wave supported_features attribute has bit 1 set if the entity is dimmable, so a light that is only dimmable but has no other features has a supported_features value of 1.  This explains why some lights were not being recognized as dimmable.  This PR changes the test to check bit 1 of the bitmask.

### CODE REVIEW

**Comment by hwhesselink** [comment]
Sorry, mistake, will submit new PR later.

**Comment by hwhesselink** [comment]
The original PR was fine, confused by a cache reload.

**Comment by hwhesselink** [comment]
I think I messed up re-opening the PR.  Please merge this if you agree with mod.

**Comment by DBuit** [comment]
Hi!

So with your change it will always be dimmable and never a switch.
You removed the treshold check and replaced it with `supportBrightness ` which is always 1 and so always dimmable.

**Comment by hwhesselink** [comment]
Hi!

I think you may be misunderstanding "supported_features": it's a bitmask and not a number, so a threshold makes no sense.  [Here](https://github.com/home-assistant/core/blob/baeb791d84035cd9bc354514ac1f5095eeb6f71c/homeassistant/components/light/__init__.py#L38-L45) (lines 38-45) is a list of the bits and as you can see bit 1 identifies if a light can set brightness (i.e. is dimmable), so my code checks to see if bit 1 is set.
My change correctly and automatically detects dimmable lights, which the current code does not - see the multiple questions on the popup card list about how to make HA recognize a lamp as dimmable.

**Comment by hwhesselink** [comment]
Not to be captain obvious but my change of course also correctly and automatically detects switches and non-dimmable lights.  Any reason not to merge this?

**Comment by DBuit** [comment]
@hwhesselink i see now u used & and not &&.
If you can fix the merge conflict for me i will merge it. thank you

**Comment by hwhesselink** [comment]
Hi @DBuit, merge conflict fixed.

**Comment by hwhesselink** [comment]
Ok, I have no idea what's happening here.  I've merged a 2-line change through Github and it's now showing a huge diff.  Guess I screwed up the merge.  I'm deleting the whole PR and submitting a new one.  Sorry for the hassle!

**Comment by hwhesselink** [comment]
I think i figured out what the problem was: you have different line-endings in the file - all of the code that I think is yours has CR-LF (Windows style) line-endings, the rest has LF (Unix style) line ending.  When I updated the merge Github gave me this message: "We’ve detected the file has mixed line endings. When you commit changes we will normalize them to Windows-style" and it did, resulting in an almost 4000 line diff...  You might want to standardize on 1 style to prevent future surprises.  I'd do 1 commit for just that - it'll be huge but you'll know there are no code changes hidden in there.

**Pull request closed without merging**
